#配置日志
#logging:
#  # 配置日志的格式
#  pattern:
#    console: "%d - %msg%n"
#  # 配置日志的路径和名称
#  file:
#    path: /Users/wangjp/Desktop/sell
#    name: sell.log
#  # 配置指定类的日志级别(默认 info)
#  level:
#    com.wangjp.sell.LoggerTest: debug

spring:
  # 配置数据库
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/sell?serverTimezone=Asia/Shanghai
  jpa:
    show-sql: true
server:
  servlet:
    # 配置项目公共前缀
    context-path: /sell
  # 配置端口
  port: 8888