spring:
  # 配置数据库
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/sell?serverTimezone=Asia/Shanghai
  jpa:
    show-sql: true
server:
  servlet:
    # 配置项目公共前缀
    context-path: /sell
  port: 8888
# 自定义的一些配置，用于 spring-security
custom:
  config:
    ignores:
      # 需要放行的 post 请求
      post:
        - "/auth/login"
        - "/auth/logout"
      # 需要放行的请求，不限方法
      pattern:
        - "/open/*"