spring:
  # 配置数据库
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://47.98.163.77:3306/sell?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
  jpa:
    show-sql: true
  redis:
    host: localhost
    port: 6379
    # 连接超时时间
    timeout: 10000ms
server:
  servlet:
    # 配置项目公共前缀
    context-path: /sell
  port: 8888
jwt:
  config:
    # JWT 加解密使用的密钥
    secret: sell-app-my-secret-username-wangjp
    # 过期时间(60*60*24)
    expiration: 86400
    # jwt存储的请求头
    token-header: Authorization
    # jwt 负载前缀
    token-prefix: Bearer
# 上传地址，需要根据自己环境自行配置
upload:
  image:
    path: G:/upload
# 自定义的一些配置，用于 spring-security
custom:
  config:
    ignores:
      # 需要放行的 post 请求
      post:
        - "/auth/login"
        - "/auth/logout"
        - "/common/**"
      # 需要放行的请求，不限方法
      pattern:
        # swagger 放行
        - "/swagger-ui/**"
        - "/swagger-resources/**"
        - "/v3/**"
        # 上传图片放行
        - "/upload/**"